// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdfzez8KjIpKzOdyO7b0zWa1eN1FCms0Q',
    appId: '1:976450895525:web:a5dd81fcc380e38d09974c',
    messagingSenderId: '976450895525',
    projectId: 'souschef-aab33',
    authDomain: 'souschef-aab33.firebaseapp.com',
    storageBucket: 'souschef-aab33.appspot.com',
    measurementId: 'G-TD7CXD1V21',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDRlqXKotVt9btahA5kY-1zzg6MSLTuRU',
    appId: '1:976450895525:android:fd9d05af051c20ae09974c',
    messagingSenderId: '976450895525',
    projectId: 'souschef-aab33',
    storageBucket: 'souschef-aab33.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7tXWPUB3el_Utz6MtQpCfcaVbUhXmU0A',
    appId: '1:976450895525:ios:cb24f96400b7513709974c',
    messagingSenderId: '976450895525',
    projectId: 'souschef-aab33',
    storageBucket: 'souschef-aab33.appspot.com',
    iosBundleId: 'com.example.sousChef',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7tXWPUB3el_Utz6MtQpCfcaVbUhXmU0A',
    appId: '1:976450895525:ios:c579983feef5ba8109974c',
    messagingSenderId: '976450895525',
    projectId: 'souschef-aab33',
    storageBucket: 'souschef-aab33.appspot.com',
    iosBundleId: 'com.example.sousChef.RunnerTests',
  );
}
